import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#121212",
        paddingHorizontal: 16,
        paddingTop: 40,
    },
    title: {
        color: "#fff",
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 20,
        textAlign: "center",
    },
    grid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 10,
    },
    categoryItem: {
        width: "42%",
        aspectRatio: 1,
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    icon: {
        width: 60,
        height: 60,
        marginBottom: 8,
        resizeMode: "contain",
    },
    categoryText: {
        color: "#000",
        fontSize: 14,
        fontWeight: "bold",
        textAlign: "center",
    },
    addButton: {
        width: "42%",
        aspectRatio: 1,
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    addItem: {
        width: "42%",
        aspectRatio: 1,
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    bottomNav: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: "row",
        justifyContent: "space-around",
        backgroundColor: "#1E1E1E",
        paddingVertical: 12,
        paddingBottom: 20,
    },
    navItem: {
        alignItems: "center",
    },
    navIcon: {
        width: 30,
        height: 30,
        marginBottom: 4,
    },
    navText: {
        color: "#fff",
        fontSize: 12,
    },
});
