import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#121212",
        paddingHorizontal: 16,
        paddingTop: 40,
    },
    title: {
        color: "#fff",
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 20,
        textAlign: "center",
    },
    grid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingHorizontal: 10,
    },
    categoryItem: {
        width: "42%",
        aspectRatio: 1,
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    icon: {
        width: 60,
        height: 60,
        marginBottom: 8,
        resizeMode: "contain",
    },
    categoryText: {
        color: "#000",
        fontSize: 14,
        fontWeight: "bold",
        textAlign: "center",
    },
    addButton: {
        width: "42%",
        aspectRatio: 1,
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    addItem: {
        width: "42%",
        aspectRatio: 1,
        backgroundColor: "#fff",
        borderRadius: 15,
        padding: 10,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 15,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        // shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 5,
    },
    bottomNav: {
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: "row",
        justifyContent: "space-around",
        backgroundColor: "#1E1E1E",
        paddingVertical: 12,
        paddingBottom: 20,
    },
    navItem: {
        alignItems: "center",
    },
    navIcon: {
        width: 30,
        height: 30,
        marginBottom: 4,
    },
    navText: {
        color: "#fff",
        fontSize: 12,
    },

    modalContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.5)",
    },
    modalContent: {
        width: 320,
        padding: 20,
        backgroundColor: "white",
        borderRadius: 10,
        alignItems: "center",
    },
    modalTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 15,
    },
    input: {
        width: "100%",
        borderWidth: 1,
        borderColor: "#ccc",
        padding: 10,
        borderRadius: 5,
        marginBottom: 10,
    },
    inputDescription: {
        height: 100,          
        borderWidth: 1,
        borderColor: "#ccc",
        padding: 10,
        borderRadius: 5,
        marginBottom: 10,
        textAlignVertical: "top", 
    },
    buttonContainer: {
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginTop: 10,
    },
    cancelButton: {
        flex: 1,
        backgroundColor: "red",
        padding: 12,
        borderRadius: 5,
        alignItems: "center",
        marginRight: 5,
    },
    saveButton: {
        flex: 1,
        backgroundColor: "blue",
        padding: 12,
        borderRadius: 5,
        alignItems: "center",
        marginLeft: 5,
    },
    buttonText: {
        color: "white",
        fontWeight: "bold",
    },
    modalOverlay: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: "rgba(0,0,0,0.5)", 
    },
    dropdownContainer: {
        width: "100%",
        marginBottom: 10, 
    },
    deleteButton: {
        position: "absolute",
        top: 8, 
        right: 8,  
        padding: 5,
        backgroundColor: "red",
        borderRadius: 5,
        width: 50,  
        height: 50
,
        alignItems: "center",
        justifyContent: "center",
    },
    deleteButton: {
        position: "absolute",
        bottom: 1,   
        right: 8,    
        backgroundColor: "rgba(255, 0, 0, 0.9)", 
        borderRadius: 8,  
        paddingVertical: 6,  
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        elevation: 3, 
    },
    
    cancelButton: {
        position: "absolute",
        bottom: 1,  
        left: 8,   
        backgroundColor: "rgba(128, 128, 128, 0.9)", 
        borderRadius: 8,
        paddingVertical: 6,
        paddingHorizontal: 12,
        alignItems: "center",
        justifyContent: "center",
        elevation: 3,
    },
    
    buttonText: {
        color: "#fff", 
        fontSize: 12,  
        fontWeight: "bold",
        textTransform: "uppercase",
    },    
    deleteIcon: {
        width: 16,  
        height: 16,
        resizeMode: "contain",
    },        
});
